# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/amazon/thor/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/amazon/thor/proprietary/vendor/etc/ad_calib.cfg:system/vendor/etc/ad_calib.cfg \
    vendor/amazon/thor/proprietary/vendor/firmware/ath6k/AR6004/hw3.0/bdata.bin:system/vendor/firmware/ath6k/AR6004/hw3.0/bdata.bin \
    vendor/amazon/thor/proprietary/vendor/firmware/ath6k/AR6004/hw3.0/boardData_Thor_ETSI.bin:system/vendor/firmware/ath6k/AR6004/hw3.0/boardData_Thor_ETSI.bin \
    vendor/amazon/thor/proprietary/vendor/firmware/ath6k/AR6004/hw3.0/boardData_Thor_ETSI_WAN.bin:system/vendor/firmware/ath6k/AR6004/hw3.0/boardData_Thor_ETSI_WAN.bin \
    vendor/amazon/thor/proprietary/vendor/firmware/ath6k/AR6004/hw3.0/boardData_Thor_FCC_WAN.bin:system/vendor/firmware/ath6k/AR6004/hw3.0/boardData_Thor_FCC_WAN.bin \
    vendor/amazon/thor/proprietary/vendor/firmware/wlan/prima/WCNSS_cfg.dat:system/vendor/firmware/wlan/prima/WCNSS_cfg.dat
